import os
from dotenv import load_dotenv
from supabase import create_client, Client
from typing import List

load_dotenv()

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_SERVICE_KEY")

if not url or not key:
    raise ValueError("CRITICAL ERROR: Supabase credentials missing in .env file.")

supabase: Client = create_client(url, key)


def save_leads_to_db(city: str, category: str, leads: list, user_id: str):
    saved_count = 0

    # 👈 NEW: Extract the real city name generated by the Reverse Geocoder!
    if city.startswith("coords:"):
        parts = city.split(",")
        # If the string has the 4th parameter (the city name), use it! Otherwise fallback.
        clean_city_name = parts[3].upper() if len(parts) > 3 else "MAP AREA"
    else:
        clean_city_name = city.upper()

    for lead in leads:
        whatsapp = lead.get('WhatsApp Link', '')
        if not whatsapp or whatsapp == 'N/A':
            continue

        try:
            master_data = {
                "city": clean_city_name,
                "category": category.upper(),
                "business_name": lead.get('Business Name', 'Unknown'),
                "review_count": lead.get('Review Count', 0),
                "website_status": lead.get('Website Faults', 'N/A'),
                "whatsapp_link": whatsapp,
                "ai_strength": lead.get('AI Strength', 'N/A'),
                "ai_weakness": lead.get('AI Weakness', 'N/A'),
                "pitch": lead.get('Pitch', '')
            }

            master_response = supabase.table("master_leads").upsert(master_data, on_conflict="whatsapp_link").execute()
            lead_id = master_response.data[0]['id']

            link_data = {
                "user_id": user_id,
                "lead_id": lead_id
            }
            supabase.table("user_unlocked_leads").upsert(link_data, on_conflict="user_id, lead_id").execute()
            saved_count += 1

        except Exception as e:
            print(f"[-] DB Link Error: {e}")
            continue

    print(f"[+] DATABASE: Successfully routed {saved_count} leads to User {user_id}'s Vault.")
    return saved_count


def get_user_vault(user_id: str):
    """Fetches leads from Supabase and formats the keys."""
    try:
        response = supabase.table('user_unlocked_leads') \
            .select('unlocked_at, master_leads(*)') \
            .eq('user_id', user_id) \
            .order('unlocked_at', desc=True) \
            .execute()

        formatted_leads = []
        for item in response.data:
            db_lead = item.get('master_leads') or {}

            raw_date = item.get('unlocked_at')
            clean_date = raw_date.split('T')[0] if raw_date else "Recent"

            formatted_leads.append({
                "Business Name": db_lead.get("business_name") or "Unknown",
                "WhatsApp Link": db_lead.get("whatsapp_link") or "N/A",
                "Website Link": "N/A",
                "Review Count": db_lead.get("review_count") or 0,
                "Website Faults": db_lead.get("website_status") or "N/A",
                "AI Strength": db_lead.get("ai_strength") or "N/A",
                "AI Weakness": db_lead.get("ai_weakness") or "N/A",
                "Pitch": db_lead.get("pitch") or "No pitch generated.",
                "City": db_lead.get("city") or "Unknown",
                "Category": db_lead.get("category") or "Unknown",
                "date_scraped": clean_date
            })

        return formatted_leads

    except Exception as e:
        print(f"[-] Vault Retrieval Error: {e}")
        return []


def delete_user_leads(user_id: str, whatsapp_links: List[str]):
    """
    BULK DELETE: Severs the link between a user and multiple leads efficiently.
    """
    try:
        # Step 1: Look up all global Lead IDs matching the array of WhatsApp links
        # Using .in_() is much faster than looping!
        lead_response = supabase.table('master_leads').select('id').in_('whatsapp_link', whatsapp_links).execute()

        if not lead_response.data:
            print("[-] Delete Error: None of those WhatsApp links were found in master_leads.")
            return False, 0

        # Extract just the ID numbers into a list: [14, 25, 88]
        lead_ids = [item['id'] for item in lead_response.data]

        # Step 2: Delete all mapping links for this user that match those IDs
        delete_response = supabase.table('user_unlocked_leads') \
            .delete() \
            .eq('user_id', user_id) \
            .in_('lead_id', lead_ids) \
            .execute()

        # Optional: Check how many were actually deleted
        deleted_count = len(delete_response.data) if delete_response.data else len(lead_ids)
        print(f"[+] Bulk Delete Success: Removed {deleted_count} links from user vault.")

        return True, deleted_count

    except Exception as e:
        print(f"[-] Bulk Delete Error: {e}")
        return False, 0