import os
from dotenv import load_dotenv
from supabase import create_client, Client
from typing import List
from datetime import datetime, timezone, timedelta

load_dotenv()

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_SERVICE_KEY")

if not url or not key:
    raise ValueError("CRITICAL ERROR: Supabase credentials missing in .env file.")

supabase: Client = create_client(url, key)


def save_leads_to_db(city: str, category: str, leads: list, user_id: str):
    saved_count = 0

    # 👈 NEW: Extract the real city name generated by the Reverse Geocoder!
    if city.startswith("coords:"):
        parts = city.split(",")
        # If the string has the 4th parameter (the city name), use it! Otherwise fallback.
        clean_city_name = parts[3].upper() if len(parts) > 3 else "MAP AREA"
    else:
        clean_city_name = city.upper()

    for lead in leads:
        whatsapp = lead.get('WhatsApp Link', '')
        if not whatsapp or whatsapp == 'N/A':
            continue

        try:
            master_data = {
                "city": clean_city_name,
                "category": category.upper(),
                "business_name": lead.get('Business Name', 'Unknown'),
                "review_count": lead.get('Review Count', 0),
                "website_status": lead.get('Website Faults', 'N/A'),
                "whatsapp_link": whatsapp,
                "ai_strength": lead.get('AI Strength', 'N/A'),
                "ai_weakness": lead.get('AI Weakness', 'N/A'),
                "pitch": lead.get('Pitch', '')
            }

            master_response = supabase.table("master_leads").upsert(master_data, on_conflict="whatsapp_link").execute()
            lead_id = master_response.data[0]['id']

            link_data = {
                "user_id": user_id,
                "lead_id": lead_id
            }
            supabase.table("user_unlocked_leads").upsert(link_data, on_conflict="user_id, lead_id").execute()
            saved_count += 1

        except Exception as e:
            print(f"[-] DB Link Error: {e}")
            continue

    print(f"[+] DATABASE: Successfully routed {saved_count} leads to User {user_id}'s Vault.")
    return saved_count


def get_user_vault(user_id: str):
    """Fetches leads from Supabase and formats the keys."""
    try:
        response = supabase.table('user_unlocked_leads') \
            .select('unlocked_at, master_leads(*)') \
            .eq('user_id', user_id) \
            .order('unlocked_at', desc=True) \
            .execute()

        formatted_leads = []
        for item in response.data:
            db_lead = item.get('master_leads') or {}

            raw_date = item.get('unlocked_at')
            clean_date = raw_date.split('T')[0] if raw_date else "Recent"

            formatted_leads.append({
                "Business Name": db_lead.get("business_name") or "Unknown",
                "WhatsApp Link": db_lead.get("whatsapp_link") or "N/A",
                "Website Link": "N/A",
                "Review Count": db_lead.get("review_count") or 0,
                "Website Faults": db_lead.get("website_status") or "N/A",
                "AI Strength": db_lead.get("ai_strength") or "N/A",
                "AI Weakness": db_lead.get("ai_weakness") or "N/A",
                "Pitch": db_lead.get("pitch") or "No pitch generated.",
                "City": db_lead.get("city") or "Unknown",
                "Category": db_lead.get("category") or "Unknown",
                "date_scraped": clean_date
            })

        return formatted_leads

    except Exception as e:
        print(f"[-] Vault Retrieval Error: {e}")
        return []


def delete_user_leads(user_id: str, whatsapp_links: List[str]):
    """
    BULK DELETE: Severs the link between a user and multiple leads efficiently.
    """
    try:
        # Step 1: Look up all global Lead IDs matching the array of WhatsApp links
        # Using .in_() is much faster than looping!
        lead_response = supabase.table('master_leads').select('id').in_('whatsapp_link', whatsapp_links).execute()

        if not lead_response.data:
            print("[-] Delete Error: None of those WhatsApp links were found in master_leads.")
            return False, 0

        # Extract just the ID numbers into a list: [14, 25, 88]
        lead_ids = [item['id'] for item in lead_response.data]

        # Step 2: Delete all mapping links for this user that match those IDs
        delete_response = supabase.table('user_unlocked_leads') \
            .delete() \
            .eq('user_id', user_id) \
            .in_('lead_id', lead_ids) \
            .execute()

        # Optional: Check how many were actually deleted
        deleted_count = len(delete_response.data) if delete_response.data else len(lead_ids)
        print(f"[+] Bulk Delete Success: Removed {deleted_count} links from user vault.")

        return True, deleted_count

    except Exception as e:
        print(f"[-] Bulk Delete Error: {e}")
        return False, 0


def update_lead_pitch(whatsapp_link: str, new_pitch: str):
    """
    Allows a user to manually edit and save the AI-generated pitch.
    """
    try:
        response = supabase.table('master_leads') \
            .update({'pitch': new_pitch}) \
            .eq('whatsapp_link', whatsapp_link) \
            .execute()

        # Check if the update actually found a row to modify
        if response.data:
            return True
        return False
    except Exception as e:
        print(f"[-] Pitch Update Error: {e}")
        return False


def get_user_profile(user_id: str):
    """
    Fetches the user's profile, tier, and credit balances.
    """
    try:
        response = supabase.table('profiles').select('*').eq('id', user_id).execute()
        if response.data:
            return response.data[0]
        return None
    except Exception as e:
        print(f"[-] Profile Fetch Error: {e}")
        return None


def deduct_user_credits(user_id: str, leads_found: int, used_ai: bool):
    """
    Safely subtracts credits from the user's balance after a successful scrape.
    """
    try:
        # 1. Fetch current balances
        profile = get_user_profile(user_id)
        if not profile:
            return False

        new_standard = max(0, profile['standard_credits'] - leads_found)

        # 2. Prepare the update payload
        update_data = {"standard_credits": new_standard}

        # 3. Only deduct AI credits if they actually used the AI feature
        if used_ai:
            update_data["ai_credits"] = max(0, profile['ai_credits'] - leads_found)

        # 4. Save the new balances to the database
        supabase.table('profiles').update(update_data).eq('id', user_id).execute()

        print(f"[+] DATABASE: Deducted {leads_found} credits from User {user_id}.")
        return True

    except Exception as e:
        print(f"[-] Credit Deduction Error: {e}")
        return False

def check_and_eval_credits(user_id: str):
    """
    Evaluates the 3-day (72-hour) reset rule using strict server UTC time.
    Replenishes allowances according to the user's assigned tier profile.
    """
    try:
        response = supabase.table('profiles').select('*').eq('id', user_id).execute()
        if not response.data:
            return None

        profile = response.data[0]
        # Parse the timestamp cleanly regardless of format trailing variants
        last_reset_str = profile['last_reset_date'].replace('Z', '+00:00')
        last_reset = datetime.fromisoformat(last_reset_str)
        now = datetime.now(timezone.utc)

        # Check if 72 hours have fully elapsed
        if now - last_reset >= timedelta(days=3):
            role = profile.get('role', 'user')

            # Tier-based limitation allocation
            if role == 'admin':
                standard_limit = 9999
                ai_limit = 9999
            elif role == 'pro':
                standard_limit = 500
                ai_limit = 100
            else:  # standard default user tier
                standard_limit = 50
                ai_limit = 10

            update_payload = {
                "standard_credits": standard_limit,
                "ai_credits": ai_limit,
                "last_reset_date": now.isoformat()
            }

            reset_response = supabase.table('profiles').update(update_payload).eq('id', user_id).execute()
            if reset_response.data:
                return reset_response.data[0]

        return profile
    except Exception as e:
        print(f"[-] Security Balance Reset Evaluation Error: {e}")
        return None